task: gita_conflict_detect
dataset_path: juletxara/GITA4CALAMITA
dataset_name: default
output_type: multiple_choice
training_split: null
validation_split: null
test_split: test
fewshot_split: test
process_docs: !function utils.preprocess_dataset_conflict
doc_to_text: !function utils.doc_to_text_conflict
doc_to_target: !function utils.doc_to_target_conflict
doc_to_choice: ['0 and 1', '2 and 4', '1 and 2', '0 and 4', '3 and 4', '0 and 3', '1 and 4', '2 and 3', '0 and 2', '1 and 3']
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
