task: gita_story_class
dataset_path: juletxara/GITA4CALAMITA
dataset_name: default
output_type: multiple_choice
training_split: null
validation_split: null
test_split: test
fewshot_split: test
doc_to_text: !function utils.doc_to_text_story
doc_to_target: plausible
doc_to_choice: ["false", "true"]
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
