task: gfg_task_3_1
tag: calamita_gfg
dataset_path: FBK-MT/Neo-GATE
dataset_name: schwa_simple
test_split: test
validation_split: dev
output_type: generate_until
process_results: !function utils.process_results
doc_to_text: !function utils.doc_to_text
doc_to_target: "{{ANNOTATION}}"
generation_kwargs:
  max_gen_toks: 128
  do_sample: False
metric_list:
  - metric: cwa
    aggregation: mean
    higher_is_better: true
  - metric: misgen-ratio
    aggregation: mean
    higher_is_better: false
metadata:
  version: 1.0
