
tag: geese
task: geese_anon_gold
dataset_path: azaninello/e-rte-3-it_4_calamita_v1.0
dataset_name: default
output_type: multiple_choice
test_split: test
validation_split: test
doc_to_text: "Your task is to predict the entailment label between two sentences, selecting one label among YES (entailment), NO (contradiction), or UNKNOWN (neutrality).
Sentence 1:{{text_t}}
Sentence 2: {{text_h}}
Hint: {{anon_gold}}.
Entailment label:"
doc_to_target: label
doc_to_choice: ["YES", "NO", "UNKNOWN"]
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true