include: base.yaml
dataset_kwargs:
  data_files:
    train: ./private_data/blm-IT/task_data/BLM-AgrIt_type-III/train.json
    test: ./private_data/blm-IT/task_data/BLM-AgrIt_type-III/test.json
task: blm_agr2_0shots

num_fewshot: 0