tag:
  - understanding
dataset_path: json
dataset_name: null
dataset_kwargs:
  data_files: ../private_data/pejorativity/pejorative_dataset_it_final.jsonl
test_split: train
task: pejorativITy-misoginy-context
doc_to_text: !function utils.genera_misoginia
doc_to_choice: ['0','1']
doc_to_target: misogyny
output_type: multiple_choice
metric_list:
  - metric: f1
    aggregation: !function utils.macro_f1_score_m
    average: macro
    hf_evaluate: true
    higher_is_better: True
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
