task: gfg_task_2_3
tag: calamita_gfg
dataset_path: FBK-MT/GeNTE
test_split: test
output_type: generate_until
process_docs: !function utils.process_docs
doc_to_text: !function utils.doc_to_text
doc_to_target: "{{GENDER}}"
generation_kwargs:
  max_gen_toks: 128
  do_sample: False
metric_list:
  - metric: !function utils.acc_gente
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
